const sequelize          = require('../config/db');
const Group              = require('./Group');
const User               = require('./User');
const Saving             = require('./Saving');
const Loan               = require('./Loan');
const Repayment          = require('./Repayment');
const AuditLog           = require('./AuditLog');
const GroupSettings      = require('./GroupSettings');
const Expenditure        = require('./Expenditure');
const Invoice            = require('./Invoice');
const Project            = require('./Project');
const ProjectContribution= require('./ProjectContribution');
const Asset              = require('./Asset');
const OtherIncome            = require('./OtherIncome');
const ProjectPendingContrib  = require('./ProjectPendingContrib');

// Associations
Group.hasMany(User,               { foreignKey: 'groupId', as: 'members' });
User.belongsTo(Group,             { foreignKey: 'groupId', as: 'group' });
Group.hasOne(GroupSettings,       { foreignKey: 'groupId', as: 'settings' });
GroupSettings.belongsTo(Group,    { foreignKey: 'groupId' });
Group.hasMany(Saving,             { foreignKey: 'groupId' });
User.hasMany(Saving,              { foreignKey: 'memberId' });
Saving.belongsTo(User,            { foreignKey: 'memberId', as: 'member' });
Group.hasMany(Loan,               { foreignKey: 'groupId' });
User.hasMany(Loan,                { foreignKey: 'memberId' });
Loan.belongsTo(User,              { foreignKey: 'memberId', as: 'member' });
Loan.hasMany(Repayment,           { foreignKey: 'loanId' });
Repayment.belongsTo(Loan,         { foreignKey: 'loanId' });
Group.hasMany(Expenditure,        { foreignKey: 'groupId' });
Group.hasMany(Invoice,            { foreignKey: 'groupId' });
Group.hasMany(Project,            { foreignKey: 'groupId' });
Project.hasMany(ProjectContribution, { foreignKey: 'projectId' });
ProjectContribution.belongsTo(Project, { foreignKey: 'projectId' });
ProjectContribution.belongsTo(User,    { foreignKey: 'memberId', as: 'member' });
Group.hasMany(Asset,              { foreignKey: 'groupId' });
Group.hasMany(OtherIncome,              { foreignKey: 'groupId' });
Project.hasMany(ProjectPendingContrib,  { foreignKey: 'projectId' });
ProjectPendingContrib.belongsTo(Project, { foreignKey: 'projectId' });
ProjectPendingContrib.belongsTo(User,    { foreignKey: 'memberId', as: 'member' });

module.exports = { sequelize, Group, User, Saving, Loan, Repayment, AuditLog, GroupSettings, Expenditure, Invoice, Project, ProjectContribution, ProjectPendingContrib, Asset, OtherIncome };
